server {
    listen 80;
    server_name localhost;

    # Bloque para manejar las peticiones a la raíz de la web
    location / {
        # 'backend' es el nombre que le pusimos al servicio en docker-compose.yml
        # 8000 es el puerto donde corre Uvicorn dentro del contenedor
        proxy_pass http://backend:8000;

        # Pasamos las cabeceras originales para que Python sepa quién nos visita
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Opcional: Configuración para manejar errores (puedes añadirla después)
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
